version: '3.7'

services:
  cmspp:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: development
    ports:
      - '80:3009'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
