## 이미지 크기를 줄이기 위해 2단계로 나눔

# 1단계
FROM node:22-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN npm i -g pnpm

# 의존성만 설치
RUN pnpm i

COPY . .

# 빌드
RUN pnpm run build


# 2단계
FROM node:22-alpine AS production

WORKDIR /usr/src/app

# 빌드된 파일만 복사
COPY --from=build /usr/src/app/dist /usr/src/app/dist

# 프로덕션 의존성만 복사
COPY --from=build /usr/src/app/node_modules /usr/src/app/node_modules

CMD ["node", "dist/main.js"]