name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  #
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Env File
        env:
          ENV: ${{secrets.ENV}}
          REFRESHTOKEN_SECRET: ${{secrets.REFRESHTOKEN_SECRET}}
          ACCESSTOKEN_SECRET: ${{secrets.ACCESSTOKEN_SECRET}}
          REDIRECT_URL: ${{secrets.REDIRECT_URL}}
          SOCIAL_CALLBACK_URL: ${{secrets.SOCIAL_CALLBACK_URL}}
          SOCIAL_GOOGLE_ID: ${{secrets.SOCIAL_GOOGLE_ID}}
          SOCIAL_GOOGLE_SECRET: ${{secrets.SOCIAL_GOOGLE_SECRET}}
          SOCIAL_KAKAO_ID: ${{secrets.SOCIAL_KAKAO_ID}}
          SOCIAL_KAKAO_SECRET: ${{secrets.SOCIAL_KAKAO_SECRET}}
          SOCIAL_NAVER_ID: ${{secrets.SOCIAL_NAVER_ID}}
          SOCIAL_NAVER_SECRET: ${{secrets.SOCIAL_NAVER_SECRET}}
        run: |
          touch test.env
          echo ENV="test" >> test.env
          echo REFRESHTOKEN_SECRET="$REFRESHTOKEN_SECRET" >> test.env
          echo ACCESSTOKEN_SECRET="$ACCESSTOKEN_SECRET" >> test.env
          echo REDIRECT_URL="$REDIRECT_URL" >> test.env
          echo SOCIAL_CALLBACK_URL="$SOCIAL_CALLBACK_URL" >> test.env
          echo SOCIAL_GOOGLE_ID="$SOCIAL_GOOGLE_ID" >> test.env
          echo SOCIAL_GOOGLE_SECRET="$SOCIAL_GOOGLE_SECRET" >> test.env
          echo SOCIAL_KAKAO_ID="$SOCIAL_KAKAO_ID" >> test.env
          echo SOCIAL_KAKAO_SECRET="$SOCIAL_KAKAO_SECRET" >> test.env
          echo SOCIAL_NAVER_ID="$SOCIAL_NAVER_ID" >> test.env
          echo SOCIAL_NAVER_SECRET="$SOCIAL_NAVER_SECRET" >> test.env
          echo "test.env created"
          cat test.env

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm test

  # #
  build:
    # test가 완료되어야 함
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_ACCESSTOKEN}}

      - name: Build and  Push Dokcer image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cmspp -f Dockerfile.prod .
          docker push ${{secrets.DOCKERHUB_USERNAME}}/cmspp
