deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        debug: true
        script: |
          # .env 파일 생성
          echo "ENV=${{ secrets.ENV }}" > .env
          echo "DB_TYPE=${{ secrets.DB_TYPE }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "REFRESHTOKEN_SECRET=${{ secrets.REFRESHTOKEN_SECRET }}" >> .env
          echo "ACCESSTOKEN_SECRET=${{ secrets.ACCESSTOKEN_SECRET }}" >> .env
          echo "REDIRECT_URL=${{ secrets.REDIRECT_URL }}" >> .env
          echo "SOCIAL_CALLBACK_URL=${{ secrets.SOCIAL_CALLBACK_URL }}" >> .env
          echo "SOCIAL_GOOGLE_ID=${{ secrets.SOCIAL_GOOGLE_ID }}" >> .env
          echo "SOCIAL_GOOGLE_SECRET=${{ secrets.SOCIAL_GOOGLE_SECRET }}" >> .env
          echo "SOCIAL_KAKAO_ID=${{ secrets.SOCIAL_KAKAO_ID }}" >> .env
          echo "SOCIAL_KAKAO_SECRET=${{ secrets.SOCIAL_KAKAO_SECRET }}" >> .env
          echo "SOCIAL_NAVER_ID=${{ secrets.SOCIAL_NAVER_ID }}" >> .env
          echo "SOCIAL_NAVER_SECRET=${{ secrets.SOCIAL_NAVER_SECRET }}" >> .env

          # .env 파일을 Docker 컨테이너에 복사하고 실행
          sudo docker stop ${{ secrets.PROJECT_NAME }}-container
          sudo docker rm ${{ secrets.PROJECT_NAME }}-container
          sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest
          sudo docker run -d -p 80:3009 --name ${{ secrets.PROJECT_NAME }}-container --env-file .env ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest
